version: '3.8'

services:
  api:
    build: .
    container_name: position-service
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - backend

networks:
  backend:
    driver: bridge
